### ISSUE TITLE
What python and Conda versions does it support?

### ISSUE THREAD

**Issue by rahul1995** [Anukriti2512/Eye-Strain-Detection#1]
Having hard time installing it. I am getting errors at some point.
I tried with Anaconda3 and python3, but then it was failing in installing requirements.txt
I tried installing python2.7 but then Anaconda 2 was not activating (maybe some anaconda issue).
Could you please help me installing this?

**Comment by Anukriti2512** [comment]
Hi @rahul1995, this project is not actively maintained, so some breaking changes in packages may cause issues. I tried installing the project and did face some issues but I was able to manually resolve them. If you can share what issues you are facing, I can help you resolve them. 

I am using:
python == 3.8.5
conda == 4.8.4
I have not tested support for other versions, so please try using these specific versions.

Some of the issues I faced while installing requirements.txt:

1) For packages showing "No matching distribution found" error, try removing the specific versions from requirements.txt for those packages.
2) For nb-conda packages, I had to explicitly install using "conda install -c conda-forge nb_conda" 
3) There's an upgrade in "MarkupSafe" where they have removed soft_unicode, so we need to install an older version. Modify requirements.txt with "MarkupSafe==2.0.1"

Thanks for bringing this to notice, I will update the project whenever I have bandwidth.

**Comment by rahul1995** [comment]
Thank you so much @Anukriti2512
It worked.
